/*
 Brev - Mail Client for macOS and iOS
 Copyright (c) 2026 Brev contributors

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the conditions in the LICENSE file.
 */

import Foundation

public struct SieveScriptPlan: Sendable, Hashable {
    public let scriptName: String
    public let script: String
    public let requiredExtensions: [String]
    public let unsupportedRules: [SieveUnsupportedRule]

    public init(
        scriptName: String,
        script: String,
        requiredExtensions: [String],
        unsupportedRules: [SieveUnsupportedRule]
    ) {
        self.scriptName = scriptName
        self.script = script
        self.requiredExtensions = requiredExtensions
        self.unsupportedRules = unsupportedRules
    }
}

public struct SieveUnsupportedRule: Sendable, Hashable {
    public let ruleID: String
    public let reasons: [String]

    public init(ruleID: String, reasons: [String]) {
        self.ruleID = ruleID
        self.reasons = reasons
    }
}

public enum SieveScriptRenderer {
    public static func renderBrevOwnedScript(
        rules: [ServerRule],
        scriptName: String = "brev-rules"
    ) -> SieveScriptPlan {
        var renderedRules = [
            "# Generated by Brev. Brev only owns this script."
        ]
        var requiredExtensions = Set<String>()
        var unsupportedRules: [SieveUnsupportedRule] = []

        for rule in rules {
            guard rule.isEnabled else {
                renderedRules.append("# Disabled rule: \(commentSafe(rule.name))")
                continue
            }

            let rulePlan = plan(rule: rule)
            if !rulePlan.unsupportedReasons.isEmpty {
                unsupportedRules.append(SieveUnsupportedRule(
                    ruleID: rule.id,
                    reasons: rulePlan.unsupportedReasons
                ))
                renderedRules.append("# Unsupported rule omitted: \(commentSafe(rule.name))")
                continue
            }

            requiredExtensions.formUnion(rulePlan.requiredExtensions)
            renderedRules.append(render(rulePlan: rulePlan))
        }

        let orderedExtensions = ["fileinto", "imap4flags"].filter(requiredExtensions.contains)
        let requireLine = orderedExtensions.isEmpty
            ? nil
            : "require [\(orderedExtensions.map { "\"\($0)\"" }.joined(separator: ", "))];"

        let script = ([requireLine].compactMap { $0 } + renderedRules)
            .joined(separator: "\n")
            .appending("\n")
        return SieveScriptPlan(
            scriptName: scriptName,
            script: script,
            requiredExtensions: orderedExtensions,
            unsupportedRules: unsupportedRules
        )
    }

    private static func plan(rule: ServerRule) -> RulePlan {
        var tests: [String] = []
        var commands: [String] = []
        var requiredExtensions = Set<String>()
        var unsupportedReasons: [String] = []

        for condition in rule.conditions {
            switch condition {
            case .senderContains(let value):
                tests.append("header :contains \"From\" \"\(quoted(value))\"")
            case .recipientContains(let value):
                tests.append("address :contains [\"To\", \"Cc\"] \"\(quoted(value))\"")
            case .subjectContains(let value):
                tests.append("header :contains \"Subject\" \"\(quoted(value))\"")
            case .hasAttachment:
                unsupportedReasons.append("Attachment tests require provider-specific Sieve extensions.")
            case .isUnread:
                unsupportedReasons.append("Unread state is not available to portable delivery-time Sieve.")
            case .providerPredicate:
                unsupportedReasons.append("Provider-specific predicates cannot be rendered to portable Sieve.")
            }
        }

        for action in rule.actions {
            switch action {
            case .moveToFolder(let id):
                requiredExtensions.insert("fileinto")
                commands.append("fileinto \"\(quoted(id))\";")
            case .archive:
                unsupportedReasons.append("Archive needs a provider-specific destination folder.")
            case .markRead:
                requiredExtensions.insert("imap4flags")
                commands.append("addflag \"\\\\Seen\";")
            case .markUnread:
                requiredExtensions.insert("imap4flags")
                commands.append("removeflag \"\\\\Seen\";")
            case .flag:
                requiredExtensions.insert("imap4flags")
                commands.append("addflag \"\\\\Flagged\";")
            case .delete:
                commands.append("discard;")
            case .forward(let address):
                commands.append("redirect \"\(quoted(address))\";")
            case .providerAction:
                unsupportedReasons.append("Provider-specific actions cannot be rendered to portable Sieve.")
            }
        }

        return RulePlan(
            tests: tests,
            commands: commands,
            requiredExtensions: requiredExtensions,
            unsupportedReasons: unsupportedReasons
        )
    }

    private static func render(rulePlan: RulePlan) -> String {
        let test = switch rulePlan.tests.count {
        case 0:
            "true"
        case 1:
            rulePlan.tests[0]
        default:
            "allof (\(rulePlan.tests.joined(separator: ", ")))"
        }

        let body = rulePlan.commands
            .map { "    \($0)" }
            .joined(separator: "\n")
        return "if \(test) {\n\(body)\n}"
    }

    /// Collapses control characters (CR/LF included) to spaces so a user-chosen
    /// rule name interpolated into a `#` comment can't inject new Sieve lines.
    private static func commentSafe(_ value: String) -> String {
        value.components(separatedBy: .controlCharacters).joined(separator: " ")
    }

    private static func quoted(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}

private struct RulePlan {
    let tests: [String]
    let commands: [String]
    let requiredExtensions: Set<String>
    let unsupportedReasons: [String]
}
