/*
 Brev - Mail Client for macOS and iOS
 Copyright (c) 2026 Brev contributors

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the conditions in the LICENSE file.
 */

@testable import BrevBackend
import Foundation
import Testing

@Suite("ManageSieveRuleSync")
struct ManageSieveRuleSyncTests {
    @Test("renders the Brev-owned script and uploads + activates it")
    func rendersAndUploads() async throws {
        let socket = ScriptedSocket(lines: [
            "\"SASL\" \"PLAIN\"", "\"SIEVE\" \"fileinto\"", "OK", // greeting
            "OK", "OK", "OK", // AUTH, PUTSCRIPT, SETACTIVE
        ])
        let sync = ManageSieveRuleSync(
            transportFactory: { NetworkManageSieveSessionTransport(socket: socket) }
        )

        let plan = try await sync.sync(
            rules: [],
            server: MailServerSettings(kind: .manageSieve, host: "sieve.x", port: 4190, tlsMode: .implicit),
            username: "alice@x.com",
            password: "pw"
        )

        #expect(plan.scriptName == "brev-rules")
        let sent = socket.sentLines.joined()
        #expect(sent.contains("PUTSCRIPT \"brev-rules\""))
        #expect(sent.contains("SETACTIVE \"brev-rules\""))
        // The rendered Brev-owned script is what got uploaded.
        #expect(sent.contains("Generated by Brev"))
    }
}
