#!/usr/bin/env bash
# scripts/install-hooks.sh — installs the Brev pre-commit hook into .git/hooks.
#
# Git does not version control its own hooks, so this script is the canonical
# source. Run once after cloning. Per ADR-0005.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK="$ROOT/.git/hooks/pre-commit"

if [[ ! -d "$ROOT/.git" ]]; then
  echo "install-hooks.sh: $ROOT is not a git work tree." >&2
  exit 1
fi

cat > "$HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — see ADR-0005.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
exec "$ROOT/scripts/lint.sh"
HOOK

chmod +x "$HOOK"
echo "install-hooks.sh: installed pre-commit hook at $HOOK"
